<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>marasm</string>
	</array>
	<key>name</key>
	<string>marASM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b([0-9,\.]+)\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(nop|mov|add|sub|mul|div|floor|ceil|push|pop|call|ret|jmp|jz|jnz|jmz|jlz|in|out|setint|int|rmint|sleep|halt)\b</string>
			<key>name</key>
			<string>keyword.marasm.instruction</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(trace|log)\b</string>
			<key>name</key>
			<string>constant.numeric.line-number.find-in-files</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(var|gvar|delv|delg)\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\;.*$)</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.character</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#json</string>
			<key>end</key>
			<string>\#end</string>
			<key>name</key>
			<string>string.header.json</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$[^\s]+)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\@[^\s]+)</string>
			<key>name</key>
			<string>storage.type.tag</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.marasm</string>
	<key>uuid</key>
	<string>e67d99a0-6c87-49b3-a8a2-d0404f93cbe0</string>
</dict>
</plist>
